version: '3.0'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'
      ZOOKEEPER_SERVERS: 'zookeeper:22888:23888'
    ports:
      - '2181:2181'
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # kafka2:
  #   image: 'confluentinc/cp-kafka:latest'
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - '9093:9093'
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        # KAFKA_LISTENERS: INSIDE://kafka2:29093,OUTSIDE://kafka2:9093
        # KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:29093,OUTSIDE://localhost:9093
        # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  # kafka3:
  #   image: 'confluentinc/cp-kafka:latest'
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - '29094:29094'
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENERS: INSIDE://kafka3:29093,OUTSIDE://kafka3:9093
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:29093,OUTSIDE://localhost:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092